"""中文关键词 → 英文术语桥接模块。

使用本地多语言 Embedding 模型做跨语言语义映射，
不依赖翻译 API，纯离线运行。

映射策略（两层）：
1. 硬编码双语对照表（精确匹配，覆盖高频专业术语）
2. FAISS 向量检索（语义近似匹配，覆盖术语库 400+ 词条）
"""

import os
from pathlib import Path

os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

_EMBED_MODEL_PATH = str(Path.home() / ".cache/modelscope/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
_EMBED_MODEL_NAME = "paraphrase-multilingual-MiniLM-L12-v2"
_EMBED_MODEL_SRC = _EMBED_MODEL_PATH if Path(_EMBED_MODEL_PATH).exists() else _EMBED_MODEL_NAME

_LIB_DIR = Path(__file__).parent
_TERMS_PATH = _LIB_DIR / "terms_en.npy"
_VECS_PATH = _LIB_DIR / "terms_en_vecs.npy"

# 硬编码双语对照表：中文术语 → 英文术语
# 覆盖多语言模型难以对齐的专业术语（如 钙钛矿↔perovskite 跨语言相似度仅 0.36）
_GLOSSARY: dict[str, str] = {
    # ── Physics / Materials ──
    "钙钛矿": "perovskite",
    "太阳能电池": "solar cell",
    "光伏": "photovoltaic",
    "半导体": "semiconductor",
    "能带": "band gap",
    "带隙": "band gap",
    "光电": "optoelectronic",
    "纳米材料": "nanomaterial",
    "石墨烯": "graphene",
    "碳纳米管": "carbon nanotube",
    "量子点": "quantum dot",
    "超导体": "superconductor",
    "铁电": "ferroelectric",
    "压电": "piezoelectric",
    "催化剂": "catalyst",
    "电极": "electrode",
    "电池": "battery",
    "超级电容器": "supercapacitor",
    "燃料电池": "fuel cell",
    "光催化": "photocatalyst",
    "电催化": "electrocatalysis",
    "热电器件": "thermoelectric",
    "热电": "thermoelectric",
    "薄膜": "thin film",
    "晶体结构": "crystal structure",
    "密度泛函": "density functional theory",
    "分子动力学": "molecular dynamics",
    "蒙特卡洛": "monte carlo simulation",
    "相变": "phase transition",
    "热导率": "thermal conductivity",
    "力学性能": "mechanical property",
    "X射线衍射": "x-ray diffraction",
    "电子显微镜": "electron microscopy",
    "拉曼光谱": "raman spectroscopy",
    "光致发光": "photoluminescence",
    "电致发光": "electroluminescence",
    "量子效率": "quantum efficiency",
    "转换效率": "power conversion efficiency",
    "开路电压": "open circuit voltage",
    "短路电流": "short circuit current",
    "电荷传输": "charge transport",
    "复合": "recombination",
    "缺陷钝化": "defect passivation",
    "界面工程": "interface engineering",
    "异质结": "heterojunction",
    "晶体管": "transistor",
    "二极管": "diode",
    "激光器": "laser",
    "发光二极管": "light emitting diode",
    "光电探测器": "photodetector",
    "传感器": "sensor",
    "能量收集": "energy harvesting",
    "储能": "energy storage",
    "锂离子电池": "lithium ion battery",
    "固态电解质": "solid state electrolyte",
    "复合材料": "composite",
    "纳米复合": "nanocomposite",
    "腐蚀": "corrosion",
    "氧化": "oxidation",
    "水解": "water splitting",
    "析氢": "hydrogen evolution reaction",
    "析氧": "oxygen evolution reaction",
    "二氧化碳还原": "carbon dioxide reduction",
    "金属有机框架": "metal organic framework",
    "共价有机框架": "covalent organic framework",
    "二维材料": "two-dimensional material",
    "过渡金属硫族化物": "transition metal dichalcogenide",
    "等离激元": "plasmonic",
    "超材料": "metamaterial",
    "光子晶体": "photonic crystal",
    "拓扑绝缘体": "topological insulator",
    "量子计算": "quantum computing",
    "量子信息": "quantum information",
    "超导量子比特": "superconducting qubit",
    "离子阱": "ion trap",
    "量子纠缠": "quantum entanglement",
    "量子纠错": "quantum error correction",
    "NV色心": "nitrogen vacancy center",
    "自旋电子学": "spintronics",
    "磁性材料": "magnetic material",
    "多铁": "multiferroic",
    "斯格明子": "skyrmion",
    # ── Computer Science / AI / ML ──
    "机器学习": "machine learning",
    "深度学习": "deep learning",
    "神经网络": "neural network",
    "卷积神经网络": "convolutional neural network",
    "循环神经网络": "recurrent neural network",
    "Transformer模型": "transformer model",
    "注意力机制": "attention mechanism",
    "自然语言处理": "natural language processing",
    "计算机视觉": "computer vision",
    "强化学习": "reinforcement learning",
    "生成对抗网络": "generative adversarial network",
    "变分自编码器": "variational autoencoder",
    "图神经网络": "graph neural network",
    "知识图谱": "knowledge graph",
    "迁移学习": "transfer learning",
    "联邦学习": "federated learning",
    "对比学习": "contrastive learning",
    "自监督学习": "self-supervised learning",
    "表示学习": "representation learning",
    "大语言模型": "large language model",
    "微调": "fine-tuning",
    "上下文学习": "in-context learning",
    "思维链": "chain of thought",
    "检索增强生成": "retrieval augmented generation",
    "词嵌入": "word embedding",
    "分词": "tokenization",
    "多头注意力": "multi-head attention",
    "位置编码": "positional encoding",
    "层归一化": "layer normalization",
    "批归一化": "batch normalization",
    "Dropout": "dropout regularization",
    "随机梯度下降": "stochastic gradient descent",
    "Adam优化器": "adam optimizer",
    "学习率": "learning rate schedule",
    "交叉熵损失": "cross entropy loss",
    "反向传播": "backpropagation",
    "过拟合": "overfitting",
    "集成学习": "ensemble learning",
    "随机森林": "random forest",
    "支持向量机": "support vector machine",
    "决策树": "decision tree",
    "K均值聚类": "k-means clustering",
    "降维": "dimensionality reduction",
    "主成分分析": "principal component analysis",
    "自编码器": "autoencoder",
    "异常检测": "anomaly detection",
    "推荐系统": "recommendation system",
    "协同过滤": "collaborative filtering",
    "情感分析": "sentiment analysis",
    "命名实体识别": "named entity recognition",
    "机器翻译": "machine translation",
    "文本摘要": "text summarization",
    "问答系统": "question answering",
    "语音识别": "speech recognition",
    "图像分类": "image classification",
    "目标检测": "object detection",
    "语义分割": "semantic segmentation",
    "扩散模型": "diffusion model",
    "贝叶斯推断": "bayesian inference",
    "高斯过程": "gaussian process",
    "Q学习": "q-learning",
    "策略梯度": "policy gradient",
    "多智能体": "multi-agent system",
    "博弈论": "game theory",
    "少样本学习": "few-shot learning",
    "零样本学习": "zero-shot learning",
    "领域自适应": "domain adaptation",
    "对抗鲁棒性": "adversarial robustness",
    "模型可解释性": "model interpretability",
    "差分隐私": "differential privacy",
    "同态加密": "homomorphic encryption",
    "区块链": "blockchain technology",
    "分布式账本": "distributed ledger",
    "共识算法": "consensus algorithm",
    "边缘计算": "edge computing",
    "云计算": "cloud computing",
    "数字孪生": "digital twin",
    "增强现实": "augmented reality",
    "虚拟现实": "virtual reality",
    "人机交互": "human computer interaction",
    "用户界面": "user interface design",
    "软件工程": "software engineering",
    "敏捷开发": "agile development",
    "DevOps": "devops",
    "持续集成": "continuous integration",
    "微服务": "microservice architecture",
    "容器编排": "container orchestration",
    "Kubernetes": "kubernetes",
    "API设计": "api design",
    "数据库": "database management",
    "SQL优化": "sql optimization",
    "NoSQL": "nosql database",
    "图数据库": "graph database",
    "时序数据库": "time series database",
    "数据仓库": "data warehouse",
    "ETL": "etl pipeline",
    "流处理": "stream processing",
    "批处理": "batch processing",
    "Spark": "apache spark",
    "Hadoop": "hadoop",
    "数据挖掘": "data mining",
    "关联规则": "association rule mining",
    "社交网络分析": "social network analysis",
    "社区发现": "community detection",
    "信息检索": "information retrieval",
    "搜索引擎": "search engine",
    "文本挖掘": "text mining",
    "网络爬虫": "web scraping",
    "数据可视化": "data visualization",
    # ── Biology / Chemistry / Medicine ──
    "基因表达": "gene expression",
    "蛋白质结构": "protein structure prediction",
    "细胞信号通路": "cell signaling pathway",
    "代谢通路": "metabolic pathway",
    "基因组测序": "genome sequencing",
    "基因编辑": "crispr gene editing",
    "表观遗传学": "epigenetics",
    "单细胞测序": "single cell sequencing",
    "药物发现": "drug discovery",
    "药物递送": "drug delivery system",
    "纳米颗粒": "nanoparticle drug carrier",
    "脂质体": "liposome formulation",
    "抗体治疗": "antibody therapy",
    "疫苗": "vaccine development",
    "免疫治疗": "cancer immunotherapy",
    "T细胞受体": "t cell receptor",
    "细胞因子风暴": "cytokine storm",
    "炎症": "inflammation pathway",
    "细胞凋亡": "apoptosis mechanism",
    "自噬": "autophagy regulation",
    "氧化应激": "oxidative stress",
    "抗氧化": "antioxidant enzyme",
    "干细胞": "stem cell therapy",
    "类器官": "organoid culture",
    "组织工程": "tissue engineering",
    "生物材料": "biomaterial scaffold",
    "水凝胶": "hydrogel synthesis",
    "生物可降解": "biodegradable polymer",
    "酶动力学": "enzyme kinetics",
    "受体结合": "receptor binding",
    "信号转导": "signal transduction pathway",
    "磷酸化": "phosphorylation cascade",
    "转录因子": "transcription factor binding",
    "DNA修复": "dna repair mechanism",
    "RNA干扰": "rna interference",
    "微小RNA": "micro rna regulation",
    "蛋白质折叠": "protein folding dynamics",
    "神经退行性疾病": "neurodegenerative disease",
    "阿尔茨海默病": "alzheimer disease mechanism",
    "帕金森病": "parkinson disease",
    "心血管疾病": "cardiovascular disease",
    "代谢综合征": "metabolic syndrome",
    "糖尿病": "diabetes mellitus",
    "传染病": "infectious disease",
    "抗病毒": "antiviral therapy",
    "抗生素耐药": "antibiotic resistance",
    "微生物组": "microbiome analysis",
    "肠脑轴": "gut brain axis",
    "益生菌": "probiotics prebiotics",
    "合成生物学": "synthetic biology",
    "代谢工程": "metabolic engineering",
    "定向进化": "directed evolution",
    "蛋白质工程": "protein engineering",
    "酶设计": "enzyme design",
    "生物催化": "biocatalysis",
    "生物合成": "biosynthesis",
    "天然产物合成": "natural product synthesis",
    "全合成": "total synthesis",
    "不对称合成": "asymmetric synthesis",
    "有机催化": "organocatalysis",
    "交叉偶联": "cross coupling reaction",
    "碳氢活化": "c-h activation",
    "光氧化还原": "photoredox catalysis",
    "电化学合成": "electrochemical synthesis",
    "流动化学": "flow chemistry",
    "点击化学": "click chemistry",
    "生物偶联": "bioconjugation",
    "多肽合成": "peptide synthesis",
    "寡核苷酸合成": "oligonucleotide synthesis",
    "聚合反应": "polymerization",
    "活性聚合": "living polymerization",
    "开环聚合": "ring opening polymerization",
    "超分子化学": "supramolecular chemistry",
    "主客体化学": "host guest chemistry",
    "分子识别": "molecular recognition",
    "自组装": "self-assembly",
    "DNA折纸": "dna origami",
    "分子机器": "molecular machine",
    "轮烷": "rotaxane",
    "配位化学": "coordination chemistry",
    "有机金属催化": "organometallic catalysis",
    "分子筛催化": "zeolite catalysis",
    # ── Engineering ──
    "控制系统": "control system design",
    "PID控制": "pid controller",
    "自适应控制": "adaptive control",
    "鲁棒控制": "robust control",
    "模型预测控制": "model predictive control",
    "卡尔曼滤波": "kalman filtering",
    "信号处理": "signal processing",
    "傅里叶变换": "fourier transform analysis",
    "小波变换": "wavelet transform",
    "图像分割": "image segmentation",
    "特征提取": "feature extraction algorithm",
    "模式识别": "pattern recognition system",
    "机器人": "robotic manipulation",
    "运动学建模": "kinematic modeling",
    "轨迹优化": "trajectory optimization",
    "SLAM": "simultaneous localization and mapping",
    "传感器融合": "sensor fusion technique",
    "有限元分析": "finite element analysis",
    "计算流体力学": "computational fluid dynamics",
    "传热": "heat transfer analysis",
    "湍流": "turbulence modeling",
    "气动设计": "aerodynamic design",
    "结构优化": "structural optimization",
    "振动分析": "vibration analysis",
    "疲劳寿命": "fatigue life prediction",
    "断裂力学": "fracture mechanics analysis",
    "摩擦涂层": "tribological coating",
    "可再生能源": "renewable energy system",
    "风力发电": "wind turbine design",
    "太阳能热": "solar thermal collector",
    "智能电网": "smart grid technology",
    "电力电子": "power electronic converter",
    "集成电路": "integrated circuit design",
    "嵌入式系统": "embedded system design",
    "实时操作系统": "real-time operating system",
    "并行计算": "parallel computing",
    "分布式计算": "distributed computing system",
    "物联网": "internet of things device",
    "无线通信": "wireless communication",
    "天线": "antenna design",
    "MIMO": "mimo system",
    "波束成形": "beamforming algorithm",
    "信道编码": "channel coding",
    "网络安全": "network security",
    "入侵检测": "intrusion detection system",
    "防火墙": "firewall configuration",
    "密码协议": "cryptographic protocol",
    "公钥基础设施": "public key infrastructure",
    "数字签名": "digital signature",
    "认证": "authentication mechanism",
    "访问控制": "access control policy",
    "零信任": "zero trust architecture",
    "软件定义网络": "software defined networking",
    "网络功能虚拟化": "network function virtualization",
    "服务质量": "quality of service",
    "拥塞控制": "congestion control",
    "路由协议": "routing protocol",
    "负载均衡": "load balancing",
    "容错": "fault tolerance",
    "灾备": "disaster recovery",
    "高可用": "high availability",
    "可扩展性": "scalability design",
    "性能优化": "performance optimization",
    "基准测试": "benchmarking methodology",
    "资源分配": "resource allocation",
    "调度算法": "scheduling algorithm",
    "工作流": "workflow management",
    "供应链": "supply chain optimization",
    "物流": "logistics planning",
    "库存管理": "inventory management",
    "制造工艺": "manufacturing process",
    "增材制造": "additive manufacturing",
    "3D打印": "3d printing technology",
    "减材制造": "subtractive manufacturing",
    "数控加工": "cnc machining",
    "激光切割": "laser cutting",
    "焊接": "welding technology",
    "表面处理": "surface treatment",
    "质量控制": "quality control",
    "统计过程控制": "statistical process control",
    "六西格玛": "six sigma methodology",
    "精益制造": "lean manufacturing",
    "工业自动化": "industrial automation",
    "PLC": "programmable logic controller",
    "SCADA": "supervisory control",
    "分布式控制系统": "distributed control system",
    "人机界面": "human machine interface",
    "工业互联网": "industrial internet",
    "工业4.0": "industry 4.0",
    "信息物理系统": "cyber-physical system",
    "数字化制造": "digital manufacturing",
    "电动汽车": "electric vehicle",
    "自动驾驶": "autonomous driving",
    "激光雷达": "lidar sensor",
    "电池管理": "battery management system",
    "电机控制": "electric motor control",
    "动力系统": "power train",
    "混合动力": "hybrid electric vehicle",
    "充电基础设施": "charging infrastructure",
    "车联网": "vehicle to grid",
    "智能交通": "intelligent transportation",
    "交通流优化": "traffic flow optimization",
    "结构健康监测": "structural health monitoring",
    "无损检测": "nondestructive testing",
    "声发射": "acoustic emission",
    "超声检测": "ultrasonic testing",
    "热成像": "thermography inspection",
    "结构动力学": "structural dynamics",
    "地震分析": "seismic analysis",
    "地震工程": "earthquake engineering",
    "风工程": "wind engineering",
    "桥梁工程": "bridge engineering",
    "岩土工程": "geotechnical engineering",
    "基础设计": "foundation design",
    "边坡稳定": "slope stability analysis",
    "隧道工程": "tunnel engineering",
    "水利工程": "hydraulic engineering",
    "水资源管理": "water resource management",
    "污水处理": "wastewater treatment",
    "空气污染": "air pollution control",
    "环境监测": "environmental monitoring",
    "气候模型": "climate modeling",
    "碳捕集": "carbon capture",
    "碳封存": "carbon sequestration",
    "生命周期评估": "life cycle assessment",
    "可持续发展": "sustainability metrics",
    # ── Rare / cross-disciplinary terms (model struggles with these) ──
    "太赫兹": "terahertz",
    "飞秒激光": "femtosecond laser",
    "等离子体": "plasmonic",
    "超表面": "metamaterial",
    "超透镜": "metalens",
    "忆阻器": "memristor",
    "纳米线": "nanowire",
    "纳米粒子": "nanoparticle",
    "纳米片": "nanosheet",
    "范德华": "van der Waals",
    "异质结构": "heterostructure",
    "莫尔超晶格": "moiré superlattice",
    "拓扑": "topological insulator",
    "外尔半金属": "weyl semimetal",
    "狄拉克半金属": "dirac semimetal",
    "量子霍尔效应": "quantum hall effect",
    "分数量子霍尔效应": "fractional quantum hall effect",
    "马约拉纳": "majorana fermion",
    "任意子": "anyon",
    "拓扑量子计算": "topological quantum computing",
    "量子密钥分发": "quantum key distribution",
    "量子隐形传态": "quantum teleportation",
    "里德堡原子": "rydberg atom",
    "光镊": "optical tweezers",
    "光力": "optomechanics",
    "声子": "phonon",
    "激子": "exciton",
    "极化子": "polariton",
    "磁振子": "magnon",
    "等离激元": "plasmon",
    "波导": "waveguide",
    "微腔": "microcavity",
    "光学频率梳": "optical frequency comb",
    "锁模激光": "mode-locked laser",
    "啁啾": "chirp",
    "孤子": "soliton",
    "非厄米": "non-Hermitian",
    "宇称时间对称": "PT-symmetry",
    "拓扑光子学": "topological photonics",
    "拓扑声子学": "topological acoustics",
    "硅光子学": "silicon photonics",
    "集成光子学": "integrated photonics",
    "神经形态": "neuromorphic computing",
    "储备池计算": "reservoir computing",
    "伊辛机": "ising machine",
    "退火": "annealing",
    "量子退火": "quantum annealing",
    "变分量子算法": "variational quantum algorithm",
    "量子模拟": "quantum simulation",
    "张量网络": "tensor network",
    "神经网络量子态": "neural quantum state",
    "生成模型": "generative model",
    "流模型": "normalizing flow",
    "分数扩散": "fractional diffusion",
    "物理信息神经网络": "physics-informed neural network",
    "算子学习": "operator learning",
    "神经算子": "neural operator",
    "图网络": "graph network",
    "等变网络": "equivariant network",
    "几何深度学习": "geometric deep learning",
    "拓扑数据分析": "topological data analysis",
    "持续同调": "persistent homology",
    "因果推断": "causal inference",
    "反事实": "counterfactual",
    "工具变量": "instrumental variable",
    "双重差分": "difference-in-differences",
    "断点回归": "regression discontinuity",
    "元学习": "meta-learning",
    "自动化机器学习": "automated machine learning",
    "神经架构搜索": "neural architecture search",
    "超参数优化": "hyperparameter optimization",
    "多模态": "multimodal",
    "视觉语言模型": "vision-language model",
    "文本到图像": "text-to-image",
    "图像描述": "image captioning",
    "视频理解": "video understanding",
    "点云": "point cloud",
    "三维重建": "3d reconstruction",
    "神经渲染": "neural rendering",
    "神经辐射场": "neural radiance field",
    "高斯散射": "gaussian splatting",
    "逆渲染": "inverse rendering",
    "隐式表示": "implicit representation",
    "符号回归": "symbolic regression",
    "方程发现": "equation discovery",
    "动力系统": "dynamical system",
    "混沌": "chaos",
    "分岔": "bifurcation",
    "同步": "synchronization",
    "涌现": "emergence",
    "耗散结构": "dissipative structure",
    "非平衡态": "non-equilibrium",
    "涨落": "fluctuation",
    "临界现象": "critical phenomenon",
    "标度律": "scaling law",
    "重整化群": "renormalization group",
    "共形场论": "conformal field theory",
    "全息原理": "holographic principle",
    "AdS/CFT": "AdS/CFT correspondence",
    "黑洞": "black hole",
    "引力波": "gravitational wave",
    "暗物质": "dark matter",
    "暗能量": "dark energy",
    "宇宙学": "cosmology",
    "暴涨": "inflation",
    "中微子": "neutrino",
    "标准模型": "standard model",
    "希格斯": "higgs boson",
    "超对称": "supersymmetry",
    "弦论": "string theory",
    "圈量子引力": "loop quantum gravity",
    "量子场论": "quantum field theory",
    "格点规范": "lattice gauge theory",
    "强关联": "strongly correlated",
    "高温超导": "high-temperature superconductor",
    "重费米子": "heavy fermion",
    "莫特绝缘体": "mott insulator",
    "电荷密度波": "charge density wave",
    "自旋密度波": "spin density wave",
    "自旋液体": "spin liquid",
    "量子相变": "quantum phase transition",
    "多体局域化": "many-body localization",
    "时间晶体": "time crystal",
    "弗洛凯": "floquet engineering",
    # ── 通信/网络工程（从100课题测试中补充） ──
    "6G": "6G communication",
    "6G通信": "6G communication",
    "确定性时延": "deterministic latency",
    "天地一体化": "space-ground integration",
    "视联网": "video networking",
    "低空智联网": "low-altitude intelligent network",
    "认知组网": "cognitive networking",
    "智算中心": "intelligent computing center",
    "光交换": "optical switching",
    "光交换网络": "optical switching network",
    "数字全息": "digital holography",
    "光场": "light field",
    "太赫兹激光器": "terahertz laser",
    "拉曼光谱": "raman spectroscopy",
    "单光子探测": "single-photon detection",
    "固态激光雷达": "solid-state lidar",
    "射频接收机": "RF receiver",
    "水声通信": "underwater acoustic communication",
    "紫外光电晶体管": "UV phototransistor",
    "宽禁带半导体": "wide bandgap semiconductor",
    "氮化镓": "GaN",
    "异质集成": "heterogeneous integration",
    "光通信": "optical communication",
    "硅基光子": "silicon photonics",
    "多维复用": "multi-dimensional multiplexing",
    "脑机接口": "brain-computer interface",
    "深空探测": "deep space exploration",
    "低轨卫星": "LEO satellite",
    "遥感影像": "remote sensing imagery",
    "光谱": "spectroscopy",
    "光子类脑计算": "photonic neuromorphic computing",
    "图像传感器": "image sensor",
    "单光子": "single photon",
    "量子密钥": "quantum key",
    "光纤激光器": "fiber laser",
    "红外热辐射": "infrared thermal radiation",
    # ── 医学/生命科学（从100课题测试中补充） ──
    "巨噬细胞": "macrophage",
    "巨噬细胞极化": "macrophage polarization",
    "肿瘤免疫微环境": "tumor immune microenvironment",
    "线粒体功能障碍": "mitochondrial dysfunction",
    "代谢性疾病": "metabolic disease",
    "铁死亡": "ferroptosis",
    "肿瘤治疗": "tumor therapy",
    "RNA修饰": "RNA modification",
    "m6A": "m6A modification",
    "心血管疾病": "cardiovascular disease",
    "外泌体": "exosome",
    "细胞间通讯": "intercellular communication",
    "神经退行性疾病": "neurodegenerative disease",
    "肠道菌群": "gut microbiota",
    "宿主代谢": "host metabolism",
    "肥胖": "obesity",
    "糖尿病": "diabetes",
    "细胞焦亡": "pyroptosis",
    "急性肺损伤": "acute lung injury",
    "基因治疗": "gene therapy",
    "医学影像": "medical imaging",
    "医学影像诊断": "medical image diagnosis",
    "蛋白设计": "protein design",
    "空间组学": "spatial omics",
    "数字染色": "digital staining",
    "心脏成像": "cardiac imaging",
    "心衰预警": "heart failure early warning",
    "肠道微生物": "gut microbiome",
    "多组学": "multi-omics",
    "核酸适配体": "aptamer",
    "靶向递送": "targeted delivery",
    "药物安全性": "drug safety",
    "毒性预测": "toxicity prediction",
    "骨关节炎": "osteoarthritis",
    "光声成像": "photoacoustic imaging",
    "光疗": "phototherapy",
    "高分辨成像": "high-resolution imaging",
    "超构表面": "metasurface",
    "全光图像处理": "all-optical image processing",
    "CRISPR": "CRISPR",
    "遗传性疾病": "genetic disease",
    "临床转化": "clinical translation",
    # ── 控制/机器人（从100课题测试中补充） ──
    "无人集群": "unmanned swarm",
    "态势评估": "situation assessment",
    "协同控制": "cooperative control",
    "避碰": "collision avoidance",
    "导引": "guidance",
    "类脑": "brain-inspired",
    "自主导航": "autonomous navigation",
    "任务分配": "task allocation",
    "三维感知": "3D perception",
    "柔顺作业": "compliant manipulation",
    "水陆自适应": "amphibious adaptation",
    "抗干扰": "anti-jamming",
    "分布式优化": "distributed optimization",
    "迁移强化学习": "transfer reinforcement learning",
    "多模态控制": "multimodal control",
    "智能协同": "intelligent cooperation",
    "无人机": "UAV",
    "无人艇": "unmanned surface vessel",
    "自主控制": "autonomous control",
    # ── 能源/环境（从100课题测试中补充） ──
    "电氢耦合": "electric-hydrogen coupling",
    "碳排放": "carbon emission",
    "双碳": "carbon peaking and carbon neutrality",
    "黄河流域": "Yellow River basin",
    "产业结构": "industrial structure",
    "生态环境": "ecological environment",
    "微塑料": "microplastics",
    "地下水": "groundwater",
    "精准农业": "precision agriculture",
    "传感器网络": "sensor network",
    "多时间尺度": "multi-time scale",
    "经济运行": "economic operation",
    "环境监测": "environmental monitoring",
    "碳中和": "carbon neutrality",
    # ── 社科/教育（从100课题测试中补充，部分术语库中无对应项直接返回英文） ──
    "乡村旅游": "rural tourism",
    "县域经济": "county economy",
    "产业融合": "industrial integration",
    "政府监管": "government regulation",
    "公共安全": "public safety",
    "特大城市": "megacity",
    "韧性治理": "resilience governance",
    "社会保障": "social security",
    "医疗体制改革": "healthcare reform",
    "共同富裕": "common prosperity",
    "粮食安全": "food security",
    "马克思主义": "Marxism",
    "中国式现代化": "Chinese-style modernization",
    "拔尖创新人才": "top innovative talents",
    "心理健康": "mental health",
    "红色基因": "revolutionary legacy",
    "跨文化传播": "cross-cultural communication",
    "国际中文教育": "international Chinese education",
    "碎片化学习": "micro-learning",
    "沉浸式学习": "immersive learning",
}

_SCORE_THRESHOLD = 0.60

# 高频噪声黑名单：在 FAISS 向量空间中充当"枢纽节点"的术语，
# 与大量无关查询的相似度异常偏高（≥0.55），但无实际语义关联。
# 这些词在 Layer 1 对照表精确匹配时可正常通过，仅过滤 Layer 2 的虚假召回。
_NOISE_TERMS: set[str] = {
    "hadoop", "skyrmion", "devops", "kubernetes",
    "zeolite catalysis", "business intelligence", "continuous integration",
    "foundation design", "kinematic modeling", "mimo system",
    "policy gradient", "self-assembly", "molecular machine",
    "coordination chemistry", "organocatalysis", "reinforcement learning agent",
    "structural optimization", "fine-tuning", "chain of thought",
    "attention mechanism", "adam optimizer", "cross coupling reaction",
    "total synthesis", "synthetic biology", "directed evolution",
    "antiviral therapy", "cancer immunotherapy", "quantum dot",
    "molecular recognition", "host guest chemistry",
    "collaborative filtering", "social network analysis",
}

_model: SentenceTransformer | None = None
_terms: np.ndarray | None = None
_term_vecs: np.ndarray | None = None
_index = None


def _load_resources() -> bool:
    global _model, _terms, _term_vecs, _index
    if not _TERMS_PATH.exists() or not _VECS_PATH.exists():
        return False
    if _index is not None:
        return True
    if _model is None:
        _model = SentenceTransformer(_EMBED_MODEL_SRC)
    _terms = np.load(_TERMS_PATH)
    _term_vecs = np.load(_VECS_PATH)
    dim = _term_vecs.shape[1]
    _index = faiss.IndexFlatIP(dim)
    _index.add(_term_vecs)
    return True


def map_chinese_to_english(
    chinese_keywords: list[str],
    top_k: int = 3,
) -> list[str]:
    """将中文关键词列表映射为英文术语列表。

    两层映射：
    1. 硬编码双语对照表精确匹配
    2. FAISS 多语言向量语义检索（得分 > 0.45 才采纳）
    3. 仍未匹配的关键词保留原文

    Args:
        chinese_keywords: 中文关键词列表，如 ["钙钛矿", "太阳能", "电池"]
        top_k: 每个中文词映射几个英文术语

    Returns:
        英文术语列表（已去重）
    """
    results: list[str] = []
    pending: list[str] = []

    # Layer 1: 硬编码双语对照表
    for kw in chinese_keywords:
        match = _GLOSSARY.get(kw)
        if match and match not in results:
            results.append(match)
        elif not match:
            pending.append(kw)

    if not pending:
        return results

    if not _load_resources():
        for kw in pending:
            if kw not in results:
                results.append(kw)
        return results

    vecs = _model.encode(pending, normalize_embeddings=True)
    k = min(top_k, _terms.shape[0])
    scores, indices = _index.search(vecs, k)

    # Layer 2: FAISS 语义检索 + 阈值过滤
    for row in range(len(pending)):
        matched = False
        for col in range(k):
            score = float(scores[row][col])
            if score < _SCORE_THRESHOLD:
                continue
            idx = int(indices[row][col])
            if idx < 0:
                continue
            term = str(_terms[idx])
            if term in _NOISE_TERMS:
                continue
            if term not in results:
                results.append(term)
                matched = True
        # Layer 3: 未达阈值的保留原文
        if not matched and pending[row] not in results:
            results.append(pending[row])

    return results
